/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuSecundario.TalentoHumano;

/**
 *
 * @author leninurbina
 */
public class pnlSecTalentoHumano extends javax.swing.JPanel {

    /**
     * Creates new form pnlSecTalentoHumano
     */
    public pnlSecTalentoHumano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConfiguracion = new javax.swing.JLabel();

        setFont(new java.awt.Font("DejaVu Sans", 1, 15)); // NOI18N
        setOpaque(false);

        lblConfiguracion.setFont(new java.awt.Font("DejaVu Sans", 1, 15)); // NOI18N
        lblConfiguracion.setText("Configuracion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblConfiguracion)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblConfiguracion)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblConfiguracion;
    // End of variables declaration//GEN-END:variables
}
