/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visMenuPrincipal.elementos;

import javax.swing.JButton;

/**
 *
 * @author leninurbina
 */
public class pnlContabilidad extends javax.swing.JPanel {

    /**
     * Creates new form pnlContabilidad
     */
    public pnlContabilidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnContabilidad = new javax.swing.JButton();

        setOpaque(false);

        btnContabilidad.setForeground(new java.awt.Color(254, 254, 254));
        btnContabilidad.setText("Contabilidad");
        btnContabilidad.setBorderPainted(false);
        btnContabilidad.setContentAreaFilled(false);
        btnContabilidad.setFocusPainted(false);
        btnContabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContabilidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnContabilidad)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnContabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnContabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContabilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContabilidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnContabilidad;
    // End of variables declaration//GEN-END:variables
public JButton getBtnContabilidad() {
        return btnContabilidad;
    }

    public void setBtnContabilidad(JButton btnContabilidad) {
        this.btnContabilidad = btnContabilidad;
    }
}
