/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuSecundario.Contabilidad;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author leninurbina
 */
public class pnlConTipoPolizas extends javax.swing.JPanel {

    /**
     * Creates new form pnlPrincipal
     */
    public pnlConTipoPolizas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTiposPolizas = new javax.swing.JButton();

        setName("pnlTipoPoliza"); // NOI18N
        setOpaque(false);

        btnTiposPolizas.setForeground(new java.awt.Color(254, 254, 254));
        btnTiposPolizas.setText("Tipos Polizas");
        btnTiposPolizas.setBorderPainted(false);
        btnTiposPolizas.setContentAreaFilled(false);
        btnTiposPolizas.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTiposPolizas)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTiposPolizas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnTiposPolizas;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnTiposPolizas() {
        return btnTiposPolizas;
    }

   }

